[package]
name = "bilateral_escrow"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.19.4"

[dependencies]
starknet = "2.19.4"
openzeppelin_access = "4.0.1"
openzeppelin_security = "4.0.1"
openzeppelin_interfaces = "2.2.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
